 # Site settings
title: "*PLAN B"
description: "Keep going"
url: "http://salee-lee.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Author Info
social:
   github: https://github.com/seula-lee
   instargram: https://instagram.com/hi.seula
   email: salee8909@gmail.com
   linkedin: www.linkedin.com/in/seul-a-grace-lee

#gems
gems:
  - jekyll-angular
  - jekyll-paginate

# Languages
lang:
  en: en
  ko: ko

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

#-------------------------------------------
# Pagination
#-------------------------------------------
# 글로벌 변수 paginator -- index.html 에서만 동작
# property
# previouse_page , next_page
# total_pages (페이지 총수)
#-------------------------------------------
paginate: 5
#paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  plan_b:
    output: true
    permalink: /plan_b/:path/
  # tags:
  #   output: true
  #   permalink: /tags/:path/
