# Site settings
title: "RECORDING ..."
description: 기록하고, 생각하고, 정리하기
url: "http://salee-lee.github.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: twitter_username
github_username:  seula-lee
email: salee8909@gmail.com

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  healing:
    output: true
    permalink: /healing/:path/
  #poetry:
  #  output: true
  #  permalink: /poetry/:path/


