# Site settings
title: "*PLAN B"
description: "기록, 생각, 정리"
url: "http://salee-lee.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Author Info
social:
   github: seula-lee
   instargram: lookat.lee
   email: salee8909@gmail.com


# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  plan_b:
    output: true
    permalink: /plan_b/:path/

